[application]
name = "chemical-balancer"
out_dir = "dist"
asset_dir = "assets"
default_platform = "desktop"

[web.app]
title = "Chemical Balancer"

[web.watcher]
watch_path = ["src"]

[web.resource]
style = []
script = []

[web.resource.dev]
script = []

[application.tools]
binaryen = { wasm_opt = true }